# Generated by Django 4.2.5 on 2023-09-21 19:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes_api', '0003_userprofile_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='user_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
